"""
Comparing the image generation process using:
1. pyroomacoustics
2. deism-arg (c++)
We compare the two methods by comparing
1. The computation time
2. The number of images generated, if they are the same
3. The image positions, if they are the same, or within a certain tolerance
!!!! You may see difference between the two methods, this is due to the numerical precision of the two methods
Difference start to appear at higher reflection orders, e.g, 9 and above
"""

import time
import numpy as np

from deism.core_deism import DEISM
from deism.core_deism_arg import (
    find_wall_centers,
    rotate_room_src_rec,
    compare_array_lists_by_distance,
)
from deism.data_loader import ConflictChecks, detect_conflicts


def load_pyroomacoustics():
    """Load pyroomacoustics only when this comparison is executed."""
    try:
        import pyroomacoustics as pra
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "examples/deism_arg_pra_compare.py requires pyroomacoustics."
        ) from exc
    return pra


def init_parameters_convex(params):
    """
    Initialize additional convex-room parameters for DEISM-ARG.
    Geometry and rotation are adapted from the original low-level example.
    """
    vertices = np.array(
        [
            [0, 0, 0],  # Origin
            [0, 0, 3.5],
            [0, 3, 2.5],
            [0, 3, 0],
            [4, 0, 0],
            [4, 0, 3.5],
            [4, 3, 2.5],
            [4, 3, 0],
        ]
    )

    if_rotate_room = 1
    room_rotation = np.array([90, 90, 90])  # [alpha, beta, gamma] in degrees

    params["vertices"] = vertices
    params["wallCenters"] = find_wall_centers(vertices)
    params["if_rotate_room"] = if_rotate_room
    params["ifRotateRoom"] = if_rotate_room
    params["room_rotation"] = room_rotation
    params["roomRotation"] = room_rotation
    params["convexCompactImages"] = 0

    if if_rotate_room:
        params = rotate_room_src_rec(params)

    pol_pra = np.array(
        [[2.5, -3], [3.5, 0], [0, 0], [0, -3]]
    ).T  # room shape after the same 90/90/90 room rotation
    height_pra = 4
    params["pol_pra"] = pol_pra
    params["height_pra"] = height_pra
    return params


def prepare_deism_arg():
    """Create a DEISM-ARG instance ready for image-generation comparison."""
    deism = DEISM("RTF", "convex")
    params = init_parameters_convex(deism.params)

    ConflictChecks.check_all_conflicts(params)
    detect_conflicts(params)

    deism.params = params
    deism.update_room(
        roomDimensions=params["vertices"],
        wallCenters=params["wallCenters"],
    )
    deism.update_wall_materials()
    deism.update_freqs()
    return deism


def main():
    pra = load_pyroomacoustics()
    deism = prepare_deism_arg()
    params = deism.params

    begin = time.time()
    deism.update_source_receiver()
    elapsed_deism_arg = time.time() - begin

    if not params["silentMode"]:
        print("[Calculating] pyroomacoustics image generation, ", end="")
    begin = time.time()
    room_pra = pra.Room.from_corners(
        params["pol_pra"],
        fs=16000,
        max_order=params["maxReflOrder"],
        ray_tracing=False,
        air_absorption=False,
    )

    room_pra.extrude(params["height_pra"])
    room_pra.add_source(params["posSource"])
    room_pra.add_microphone(params["posReceiver"])
    room_pra.image_source_model()
    elapsed_pra = time.time() - begin

    if not params["silentMode"]:
        minutes, seconds = divmod(elapsed_pra, 60)
        print(f"Done [{int(minutes)} minutes, {seconds:.3f} seconds]", end="\n\n")
        speedup = elapsed_pra / elapsed_deism_arg if elapsed_deism_arg > 0 else np.inf
        print(
            "[Info] DEISM-ARG (c++) is {} times faster than pyroomacoustics. ".format(
                speedup
            ),
            end="\n\n",
        )

    round_decimal = 3
    images_deism_arg = np.asarray(deism.room_convex.sources).T.round(
        decimals=round_decimal
    )
    images_pra = room_pra.sources[0].images.T.round(decimals=round_decimal)

    if not params["silentMode"]:
        print("[Checking] Image number: ", end="\n")
        print(f"Images generated by pyroomacoustics is {len(images_pra)}, ", end="")
        print(
            f"Images generated by DEISM-ARG (C++) is {len(images_deism_arg)}. ",
            end="\n\n",
        )
        print(
            "[Checking] If the images are the same between DEISM-ARG (c++) and pyroomacoustics:",
            end="\n",
        )

    compare_array_lists_by_distance(
        list(images_pra),
        list(images_deism_arg),
        ["pyroomacoustics", "DEISM-ARG (C++)"],
        tolerance=1e-5,
    )


# -------------------------------------------------------
if __name__ == "__main__":
    main()
