import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np

from deism.core_deism import DEISM


PIPELINE_STEPS = [
    ("update_room", "update_room"),
    ("update_wall_materials", "update_wall_materials"),
    ("update_freqs", "update_freqs"),
    ("update_source_receiver", "update_source_receiver"),
    ("update_directivities", "update_directivities"),
]


def value_signature(value: Any) -> Any:
    if isinstance(value, np.ndarray):
        return ("ndarray", value.shape, str(value.dtype))
    if isinstance(value, dict):
        keys = tuple(sorted(value.keys()))
        return ("dict", len(value), keys)
    if isinstance(value, (list, tuple)):
        return (type(value).__name__, len(value))
    if isinstance(value, (int, float, str, bool, type(None), complex)):
        return (type(value).__name__, value)
    return (type(value).__name__,)


def snapshot_signatures(params: Dict[str, Any]) -> Dict[str, Any]:
    return {k: value_signature(v) for k, v in params.items()}


def diff_snapshots(
    before: Dict[str, Any], after: Dict[str, Any]
) -> Dict[str, List[str]]:
    b_keys = set(before.keys())
    a_keys = set(after.keys())
    added = sorted(a_keys - b_keys)
    removed = sorted(b_keys - a_keys)
    changed = sorted(k for k in (b_keys & a_keys) if before[k] != after[k])
    return {"added": added, "removed": removed, "changed": changed}


def run_pipeline(roomtype: str, mode: str, method: str) -> Dict[str, Any]:
    saved_argv = list(sys.argv)
    try:
        # DEISM constructor parses CLI args. Isolate this tool's arguments.
        sys.argv = [saved_argv[0]]
        deism = DEISM(mode, roomtype)
    finally:
        sys.argv = saved_argv

    deism.params["silentMode"] = 1
    deism.params["DEISM_method"] = method

    report: Dict[str, Any] = {
        "roomtype": roomtype,
        "mode": mode,
        "method": method,
        "notes": [],
        "steps": {},
    }

    for step_name, method_name in PIPELINE_STEPS:
        fn = getattr(deism, method_name)
        before = snapshot_signatures(deism.params)
        fn()
        after = snapshot_signatures(deism.params)
        diff = diff_snapshots(before, after)
        touched = sorted(set(diff["added"] + diff["changed"]))
        report["steps"][step_name] = {
            "added": diff["added"],
            "removed": diff["removed"],
            "changed": diff["changed"],
            "touched": touched,
        }

    return report


def compare_reports(shoebox: Dict[str, Any], convex: Dict[str, Any]) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    for step_name, _ in PIPELINE_STEPS:
        s = set(shoebox["steps"][step_name]["touched"])
        c = set(convex["steps"][step_name]["touched"])
        out[step_name] = {
            "common_touched": sorted(s & c),
            "shoebox_only_touched": sorted(s - c),
            "convex_only_touched": sorted(c - s),
        }
    return out


def write_markdown(
    shoebox: Dict[str, Any],
    convex: Dict[str, Any],
    comparison: Dict[str, Any],
    path: Path,
):
    lines = [
        "# DEISM Runtime Dependency Comparison",
        "",
        "Generated by `tools/deism_dependency_compare.py`.",
        "",
        f"- Mode: `{shoebox['mode']}`",
        f"- Method: `{shoebox['method']}`",
        "",
    ]
    for step_name, _ in PIPELINE_STEPS:
        lines.append(f"## `{step_name}`")
        lines.append("")
        lines.append(
            "- Common touched keys: "
            + (
                ", ".join(f"`{k}`" for k in comparison[step_name]["common_touched"])
                or "None"
            )
        )
        lines.append(
            "- Shoebox-only touched keys: "
            + (
                ", ".join(
                    f"`{k}`" for k in comparison[step_name]["shoebox_only_touched"]
                )
                or "None"
            )
        )
        lines.append(
            "- Convex-only touched keys: "
            + (
                ", ".join(
                    f"`{k}`" for k in comparison[step_name]["convex_only_touched"]
                )
                or "None"
            )
        )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Compare runtime parameter dependencies for shoebox vs convex."
    )
    parser.add_argument("--mode", default="RTF", choices=["RTF", "RIR"])
    parser.add_argument("--method", default="LC", choices=["LC", "ORG", "MIX"])
    parser.add_argument(
        "--out-json", default="tools/reports/deism_dependency_compare.json"
    )
    parser.add_argument("--out-md", default="tools/reports/deism_dependency_compare.md")
    args = parser.parse_args()

    shoebox = run_pipeline("shoebox", args.mode, args.method)
    convex = run_pipeline("convex", args.mode, args.method)
    comparison = compare_reports(shoebox, convex)

    out = {
        "shoebox": shoebox,
        "convex": convex,
        "comparison": comparison,
    }

    out_json = Path(args.out_json)
    out_md = Path(args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(out, indent=2), encoding="utf-8")
    write_markdown(shoebox, convex, comparison, out_md)
    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")


if __name__ == "__main__":
    main()
