import json
from pathlib import Path
from statistics import median
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from profile_image_generation import profile_image_generation


def _scenario_name(cfg):
    if cfg["mode"] == "RTF":
        freq_desc = f"{int(cfg['start_freq'])}-{int(cfg['end_freq'])}Hz_step{int(cfg['freq_step'])}"
    else:
        freq_desc = f"sr{cfg['sample_rate']}_rir{cfg['rir_length']}"
    return (
        f"{cfg['roomtype']}_{cfg['mode']}_{cfg['method']}"
        f"_ro{cfg['max_refl_order']}_sh{cfg['sh_order']}_{freq_desc}"
    )


def _write_markdown(path: Path, reports):
    lines = [
        "# Image Stage Baseline Report",
        "",
        "Generated by `tools/run_image_stage_baseline.py`.",
        "",
        "## Scenarios",
        "",
    ]
    for r in reports:
        c = r["config"]
        m = r["memory"]
        t = r["timing_s"]
        lines.append(f"### `{r['name']}`")
        lines.append(
            f"- room/mode/method: `{c['roomtype']}` / `{c['mode']}` / `{c['method']}`"
        )
        lines.append(
            f"- reflection order / SH order: `{c['max_refl_order']}` / `{c['sh_order']}`"
        )
        lines.append(
            f"- n_images / n_freqs: `{r['counts']['n_images']}` / `{r['counts']['n_freqs']}`"
        )
        lines.append(
            f"- image generation time: `{t['image_generation']:.3f} s` (prep `{t['prep_before_image_gen']:.3f} s`)"
        )
        lines.append(
            f"- image arrays memory: `{m['images_total_array_bytes'] / (1024**2):.2f} MB`"
        )
        lines.append(
            f"- merged estimate (complex128): `{m['estimated_merged_image_bytes_complex128'] / (1024**2):.2f} MB`"
        )
        lines.append(
            f"- RAM budget status (16GB * 0.75): `{m['budget_check']['status']}`"
        )
        lines.append("")

    if reports:
        img_times = [r["timing_s"]["image_generation"] for r in reports]
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- scenarios: `{len(reports)}`")
        lines.append(f"- image generation time median: `{median(img_times):.3f} s`")
        lines.append(f"- image generation time max: `{max(img_times):.3f} s`")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    scenarios = [
        {
            "roomtype": "shoebox",
            "mode": "RTF",
            "method": "LC",
            "max_refl_order": 10,
            "sh_order": 3,
            "start_freq": 200.0,
            "end_freq": 2200.0,
            "freq_step": 100.0,
            "sample_rate": 48000,
            "rir_length": 0.4,
            "num_para_images": 16,
            "ray_batch_size": 16,
            "accel_enabled": False,
            "accel_shoebox_images": False,
            "accel_use_torch": False,
            "max_ram_gb": 16.0,
            "safety_fraction": 0.75,
        },
        {
            "roomtype": "shoebox",
            "mode": "RTF",
            "method": "LC",
            "max_refl_order": 20,
            "sh_order": 5,
            "start_freq": 100.0,
            "end_freq": 5000.0,
            "freq_step": 50.0,
            "sample_rate": 48000,
            "rir_length": 0.4,
            "num_para_images": 16,
            "ray_batch_size": 16,
            "accel_enabled": False,
            "accel_shoebox_images": False,
            "accel_use_torch": False,
            "max_ram_gb": 16.0,
            "safety_fraction": 0.75,
        },
        {
            "roomtype": "convex",
            "mode": "RTF",
            "method": "LC",
            "max_refl_order": 5,
            "sh_order": 3,
            "start_freq": 200.0,
            "end_freq": 2200.0,
            "freq_step": 100.0,
            "sample_rate": 48000,
            "rir_length": 0.4,
            "num_para_images": 16,
            "ray_batch_size": 16,
            "accel_enabled": False,
            "accel_shoebox_images": False,
            "accel_use_torch": False,
            "max_ram_gb": 16.0,
            "safety_fraction": 0.75,
        },
    ]

    reports = []
    for cfg in scenarios:
        report = profile_image_generation(cfg)
        report["name"] = _scenario_name(cfg)
        reports.append(report)

    out_json = Path("tools/reports/image_stage_baseline.json")
    out_md = Path("tools/reports/image_stage_baseline.md")
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"reports": reports}, indent=2), encoding="utf-8")
    _write_markdown(out_md, reports)
    print(f"Wrote {out_json}")
    print(f"Wrote {out_md}")


if __name__ == "__main__":
    main()
