name: Auto Release

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/**'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    if: '!contains(github.event.head_commit.message, ''[skip ci]'')'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Get current version
        id: current_version
        run: |
          # Extract version from deism/version.py
          if [ -f "deism/version.py" ]; then
            VERSION=$(python -c "exec(open('deism/version.py').read()); print(__version__)")
          elif [ -f "setup.py" ]; then
            VERSION=$(python setup.py --version)
          elif [ -f "pyproject.toml" ]; then
            VERSION=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
          else
            echo "No version file found"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_exists
        run: |
          if git rev-parse "v${{ steps.current_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.tag_exists.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current_version.outputs.version }}
          release_name: Release v${{ steps.current_version.outputs.version }}
          body: |
            Auto-generated release for version ${{ steps.current_version.outputs.version }}
            
            Changes in this release:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false 